### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by garronej** [garronej/denoify#26]
# TODO LIST / Things that need to change

- [ ] Improve documentation. (New website incoming)
- [ ] Gather all imports in a `/deps.ts` [oscarotero/nodedeno](https://github.com/oscarotero/nodedeno) does.
- [ ] Support `baseUrl` tsConfig option. (Import non relative path relative to `baseUrl`)
- [x] Support `myModule.deno.ts` alongside `myModule.ts` for deno specific implementation of part of the code. (Like in React Native)
- [x] Support custom `import/export` statements replacer.
- [x] 🔥 Leverage CDNs like [Skypack](https://www.skypack.dev) (ex [Pika](https://www.pika.dev/cdn)) or [jspm](https://jspm.org) to support more NPM modules out of the box, feature [side loading of type definitions](https://user-images.githubusercontent.com/6702424/85604253-6ae1a380-b651-11ea-9406-38bb57f190de.png). 
- [x] Support `.tsx`
